/**
 * Comprehensive Seed Database Script
 * Populates database with 30 diverse restaurants and 5 unique dishes each
 */

import mongoose from 'mongoose';
import { config } from '../config/environment';
import Restaurant from '../models/Restaurant';
import MenuItem from '../models/MenuItem';
import logger from '../utils/logger';

// 30 Diverse Restaurants
const restaurants = [
  // American - Burgers
  {
    name: 'Burger Bliss',
    description: 'Premium gourmet burgers made with grass-fed beef and artisan buns',
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800',
    rating: 4.8,
    reviewCount: 256,
    deliveryTime: 15,
    deliveryFee: 0,
    categories: ['Burger', 'American'],
    isFreeDelivery: true,
    isPopular: true,
    address: '789 Burger Lane, Downtown',
    distance: 0.8,
  },
  {
    name: 'The Burger Joint',
    description: 'Classic American burgers with a modern twist',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800',
    rating: 4.6,
    reviewCount: 189,
    deliveryTime: 20,
    deliveryFee: 2.99,
    categories: ['Burger', 'Fast Food'],
    isFreeDelivery: false,
    isPopular: true,
    address: '456 Food Street',
    distance: 1.5,
  },

  // Italian - Pizza & Pasta
  {
    name: 'Pizza Palace',
    description: 'Authentic wood-fired Neapolitan pizzas',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
    rating: 4.7,
    reviewCount: 312,
    deliveryTime: 30,
    deliveryFee: 1.99,
    categories: ['Pizza', 'Italian'],
    isFreeDelivery: false,
    isPopular: true,
    address: '321 Pizza Plaza',
    distance: 2.2,
  },
  {
    name: 'Bella Pasta',
    description: 'Homemade pasta and traditional Italian cuisine',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800',
    rating: 4.9,
    reviewCount: 428,
    deliveryTime: 35,
    deliveryFee: 0,
    categories: ['Italian', 'Pasta'],
    isFreeDelivery: true,
    isPopular: true,
    address: '654 Little Italy Ave',
    distance: 3.1,
  },
  {
    name: 'Trattoria Rosa',
    description: 'Family-style Italian restaurant with wine selection',
    imageUrl: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
    rating: 4.5,
    reviewCount: 178,
    deliveryTime: 40,
    deliveryFee: 3.99,
    categories: ['Italian', 'Fine Dining'],
    isFreeDelivery: false,
    isPopular: false,
    address: '123 Vineyard Road',
    distance: 4.5,
  },

  // Asian - Chinese
  {
    name: 'Golden Dragon',
    description: 'Authentic Szechuan and Cantonese cuisine',
    imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800',
    rating: 4.6,
    reviewCount: 234,
    deliveryTime: 25,
    deliveryFee: 0,
    categories: ['Asian', 'Chinese'],
    isFreeDelivery: true,
    isPopular: true,
    address: '888 Dragon Street',
    distance: 2.0,
  },
  {
    name: 'Dim Sum House',
    description: 'Traditional dim sum and Chinese specialties',
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800',
    rating: 4.7,
    reviewCount: 301,
    deliveryTime: 30,
    deliveryFee: 2.49,
    categories: ['Asian', 'Chinese', 'Dim Sum'],
    isFreeDelivery: false,
    isPopular: true,
    address: '567 Chinatown Blvd',
    distance: 2.8,
  },

  // Asian - Japanese
  {
    name: 'Sushi Master',
    description: 'Fresh sushi and sashimi from expert chefs',
    imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800',
    rating: 4.9,
    reviewCount: 467,
    deliveryTime: 35,
    deliveryFee: 3.99,
    categories: ['Asian', 'Japanese', 'Sushi'],
    isFreeDelivery: false,
    isPopular: true,
    address: '987 Sushi Ave',
    distance: 3.5,
  },
  {
    name: 'Ramen Kingdom',
    description: 'Authentic Japanese ramen with rich broths',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800',
    rating: 4.8,
    reviewCount: 389,
    deliveryTime: 25,
    deliveryFee: 0,
    categories: ['Asian', 'Japanese', 'Ramen'],
    isFreeDelivery: true,
    isPopular: true,
    address: '432 Noodle Lane',
    distance: 1.9,
  },

  // Asian - Thai
  {
    name: 'Thai Spice',
    description: 'Aromatic Thai curries and street food favorites',
    imageUrl: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800',
    rating: 4.7,
    reviewCount: 276,
    deliveryTime: 30,
    deliveryFee: 2.99,
    categories: ['Asian', 'Thai'],
    isFreeDelivery: false,
    isPopular: true,
    address: '789 Bangkok Street',
    distance: 2.5,
  },

  // Asian - Korean
  {
    name: 'Seoul Kitchen',
    description: 'Korean BBQ and traditional dishes',
    imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800',
    rating: 4.8,
    reviewCount: 342,
    deliveryTime: 35,
    deliveryFee: 0,
    categories: ['Asian', 'Korean'],
    isFreeDelivery: true,
    isPopular: true,
    address: '234 Seoul Plaza',
    distance: 3.2,
  },

  // Asian - Vietnamese
  {
    name: 'Pho Heaven',
    description: 'Traditional Vietnamese pho and banh mi',
    imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800',
    rating: 4.6,
    reviewCount: 198,
    deliveryTime: 20,
    deliveryFee: 1.99,
    categories: ['Asian', 'Vietnamese'],
    isFreeDelivery: false,
    isPopular: false,
    address: '567 Hanoi Road',
    distance: 2.1,
  },

  // Mexican
  {
    name: 'Taco Fiesta',
    description: 'Authentic Mexican street tacos and burritos',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
    rating: 4.7,
    reviewCount: 289,
    deliveryTime: 20,
    deliveryFee: 0,
    categories: ['Mexican', 'Tacos'],
    isFreeDelivery: true,
    isPopular: true,
    address: '654 Taco Street',
    distance: 1.6,
  },
  {
    name: 'El Mariachi',
    description: 'Traditional Mexican cuisine with margaritas',
    imageUrl: 'https://images.unsplash.com/photo-1613514785940-daed07799d9b?w=800',
    rating: 4.5,
    reviewCount: 167,
    deliveryTime: 30,
    deliveryFee: 2.99,
    categories: ['Mexican'],
    isFreeDelivery: false,
    isPopular: false,
    address: '321 Fiesta Boulevard',
    distance: 3.0,
  },

  // Indian
  {
    name: 'Spice Route',
    description: 'North and South Indian curries and tandoori',
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800',
    rating: 4.8,
    reviewCount: 356,
    deliveryTime: 35,
    deliveryFee: 0,
    categories: ['Asian', 'Indian'],
    isFreeDelivery: true,
    isPopular: true,
    address: '789 Curry Lane',
    distance: 2.7,
  },
  {
    name: 'Tandoor Palace',
    description: 'Authentic tandoori and biryani specialties',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800',
    rating: 4.6,
    reviewCount: 223,
    deliveryTime: 40,
    deliveryFee: 3.49,
    categories: ['Asian', 'Indian'],
    isFreeDelivery: false,
    isPopular: true,
    address: '456 Spice Market',
    distance: 3.8,
  },

  // Mediterranean & Middle Eastern
  {
    name: 'Mediterranean Delight',
    description: 'Fresh Greek and Mediterranean flavors',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
    rating: 4.7,
    reviewCount: 245,
    deliveryTime: 25,
    deliveryFee: 2.49,
    categories: ['Mediterranean', 'Greek'],
    isFreeDelivery: false,
    isPopular: true,
    address: '123 Athens Street',
    distance: 2.3,
  },
  {
    name: 'Falafel King',
    description: 'Middle Eastern wraps and mezze platters',
    imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    rating: 4.5,
    reviewCount: 178,
    deliveryTime: 20,
    deliveryFee: 0,
    categories: ['Middle Eastern', 'Mediterranean'],
    isFreeDelivery: true,
    isPopular: false,
    address: '789 Lebanon Ave',
    distance: 1.7,
  },

  // BBQ & Steakhouse
  {
    name: 'Smoke & Fire BBQ',
    description: 'Slow-smoked meats and Southern BBQ',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
    rating: 4.9,
    reviewCount: 412,
    deliveryTime: 35,
    deliveryFee: 0,
    categories: ['BBQ', 'American'],
    isFreeDelivery: true,
    isPopular: true,
    address: '567 BBQ Boulevard',
    distance: 3.4,
  },
  {
    name: 'Prime Steakhouse',
    description: 'Premium aged steaks and fine dining',
    imageUrl: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800',
    rating: 4.8,
    reviewCount: 298,
    deliveryTime: 45,
    deliveryFee: 4.99,
    categories: ['Steakhouse', 'Fine Dining'],
    isFreeDelivery: false,
    isPopular: true,
    address: '234 Steakhouse Row',
    distance: 4.2,
  },

  // Seafood
  {
    name: 'Ocean\'s Catch',
    description: 'Fresh seafood and coastal favorites',
    imageUrl: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=800',
    rating: 4.7,
    reviewCount: 267,
    deliveryTime: 40,
    deliveryFee: 3.99,
    categories: ['Seafood'],
    isFreeDelivery: false,
    isPopular: true,
    address: '890 Harbor Drive',
    distance: 4.0,
  },

  // Vegan & Healthy
  {
    name: 'Green Leaf Café',
    description: 'Plant-based meals and organic smoothies',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
    rating: 4.6,
    reviewCount: 189,
    deliveryTime: 25,
    deliveryFee: 0,
    categories: ['Vegan', 'Healthy'],
    isFreeDelivery: true,
    isPopular: true,
    address: '345 Wellness Way',
    distance: 2.0,
  },
  {
    name: 'Fresh & Fit',
    description: 'Nutritious bowls and protein-packed meals',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
    rating: 4.5,
    reviewCount: 156,
    deliveryTime: 20,
    deliveryFee: 2.49,
    categories: ['Healthy', 'Salads'],
    isFreeDelivery: false,
    isPopular: false,
    address: '678 Fitness Street',
    distance: 1.8,
  },

  // Breakfast & Brunch
  {
    name: 'Morning Glory',
    description: 'All-day breakfast and brunch favorites',
    imageUrl: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=800',
    rating: 4.7,
    reviewCount: 234,
    deliveryTime: 25,
    deliveryFee: 0,
    categories: ['Breakfast', 'Brunch'],
    isFreeDelivery: true,
    isPopular: true,
    address: '123 Sunrise Avenue',
    distance: 1.4,
  },

  // Sandwiches & Deli
  {
    name: 'Artisan Deli',
    description: 'Gourmet sandwiches and fresh-baked bread',
    imageUrl: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=800',
    rating: 4.6,
    reviewCount: 201,
    deliveryTime: 15,
    deliveryFee: 1.99,
    categories: ['Sandwiches', 'Deli'],
    isFreeDelivery: false,
    isPopular: true,
    address: '456 Deli Lane',
    distance: 1.2,
  },

  // Desserts & Bakery
  {
    name: 'Sweet Treats Bakery',
    description: 'Artisan pastries, cakes, and desserts',
    imageUrl: 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=800',
    rating: 4.9,
    reviewCount: 378,
    deliveryTime: 20,
    deliveryFee: 0,
    categories: ['Dessert', 'Bakery'],
    isFreeDelivery: true,
    isPopular: true,
    address: '789 Sweet Street',
    distance: 1.6,
  },

  // Chicken & Wings
  {
    name: 'Wing Stop Express',
    description: 'Crispy wings with signature sauces',
    imageUrl: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=800',
    rating: 4.5,
    reviewCount: 267,
    deliveryTime: 20,
    deliveryFee: 2.49,
    categories: ['Chicken', 'Fast Food'],
    isFreeDelivery: false,
    isPopular: true,
    address: '234 Wing Avenue',
    distance: 2.1,
  },

  // Comfort Food
  {
    name: 'Comfort Kitchen',
    description: 'Homestyle cooking and comfort classics',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
    rating: 4.6,
    reviewCount: 198,
    deliveryTime: 30,
    deliveryFee: 0,
    categories: ['American', 'Comfort Food'],
    isFreeDelivery: true,
    isPopular: false,
    address: '567 Home Street',
    distance: 2.6,
  },

  // Fusion
  {
    name: 'Fusion Lab',
    description: 'Creative fusion cuisine from around the world',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    rating: 4.8,
    reviewCount: 312,
    deliveryTime: 35,
    deliveryFee: 3.49,
    categories: ['Fusion', 'International'],
    isFreeDelivery: false,
    isPopular: true,
    address: '890 Innovation Drive',
    distance: 3.6,
  },

  // Caribbean
  {
    name: 'Island Vibes',
    description: 'Caribbean jerk chicken and island specialties',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
    rating: 4.7,
    reviewCount: 223,
    deliveryTime: 30,
    deliveryFee: 2.99,
    categories: ['Caribbean'],
    isFreeDelivery: false,
    isPopular: false,
    address: '345 Tropical Way',
    distance: 3.1,
  },
];

// Menu items data structure for each restaurant type
const menuItemsByType: Record<string, any[]> = {
  burger: [
    {
      name: 'Classic Beef Burger',
      description: 'Juicy beef patty with lettuce, tomato, onion, and special sauce',
      imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800',
      price: 12.99,
      category: 'Burgers',
      isVegetarian: false,
      ingredients: ['Beef Patty', 'Lettuce', 'Tomato', 'Onion', 'Special Sauce', 'Brioche Bun'],
    },
    {
      name: 'BBQ Bacon Burger',
      description: 'Smoky BBQ sauce, crispy bacon, cheddar cheese, and onion rings',
      imageUrl: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=800',
      price: 15.99,
      category: 'Burgers',
      isVegetarian: false,
      ingredients: ['Beef Patty', 'BBQ Sauce', 'Bacon', 'Cheddar', 'Onion Rings'],
    },
    {
      name: 'Mushroom Swiss Burger',
      description: 'Sautéed mushrooms, Swiss cheese, and truffle aioli',
      imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800',
      price: 14.99,
      category: 'Burgers',
      isVegetarian: false,
      ingredients: ['Beef Patty', 'Mushrooms', 'Swiss Cheese', 'Truffle Aioli'],
    },
    {
      name: 'Veggie Burger',
      description: 'Plant-based patty with avocado and fresh vegetables',
      imageUrl: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=800',
      price: 11.99,
      category: 'Burgers',
      isVegetarian: true,
      ingredients: ['Plant Patty', 'Avocado', 'Lettuce', 'Tomato', 'Whole Wheat Bun'],
    },
    {
      name: 'Spicy Jalapeño Burger',
      description: 'Pepper jack cheese, jalapeños, and chipotle mayo',
      imageUrl: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=800',
      price: 13.99,
      category: 'Burgers',
      isVegetarian: false,
      ingredients: ['Beef Patty', 'Jalapeños', 'Pepper Jack', 'Chipotle Mayo'],
    },
  ],
  pizza: [
    {
      name: 'Margherita Pizza',
      description: 'Classic tomato sauce, fresh mozzarella, and basil',
      imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800',
      price: 14.99,
      category: 'Pizza',
      isVegetarian: true,
      ingredients: ['Tomato Sauce', 'Mozzarella', 'Fresh Basil', 'Olive Oil'],
    },
    {
      name: 'Pepperoni Supreme',
      description: 'Loaded with pepperoni and extra cheese',
      imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800',
      price: 16.99,
      category: 'Pizza',
      isVegetarian: false,
      ingredients: ['Tomato Sauce', 'Mozzarella', 'Pepperoni', 'Oregano'],
    },
    {
      name: 'BBQ Chicken Pizza',
      description: 'Grilled chicken, BBQ sauce, red onions, and cilantro',
      imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
      price: 17.99,
      category: 'Pizza',
      isVegetarian: false,
      ingredients: ['BBQ Sauce', 'Chicken', 'Red Onion', 'Mozzarella', 'Cilantro'],
    },
    {
      name: 'Vegetarian Deluxe',
      description: 'Bell peppers, mushrooms, olives, onions, and tomatoes',
      imageUrl: 'https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=800',
      price: 15.99,
      category: 'Pizza',
      isVegetarian: true,
      ingredients: ['Tomato Sauce', 'Bell Peppers', 'Mushrooms', 'Olives', 'Onions'],
    },
    {
      name: 'Meat Lovers',
      description: 'Pepperoni, sausage, bacon, and ham',
      imageUrl: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=800',
      price: 18.99,
      category: 'Pizza',
      isVegetarian: false,
      ingredients: ['Pepperoni', 'Italian Sausage', 'Bacon', 'Ham', 'Mozzarella'],
    },
  ],
  italian: [
    {
      name: 'Spaghetti Carbonara',
      description: 'Creamy egg sauce with pancetta and parmesan',
      imageUrl: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800',
      price: 16.99,
      category: 'Pasta',
      isVegetarian: false,
      ingredients: ['Spaghetti', 'Eggs', 'Pancetta', 'Parmesan', 'Black Pepper'],
    },
    {
      name: 'Fettuccine Alfredo',
      description: 'Rich and creamy parmesan sauce',
      imageUrl: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=800',
      price: 15.99,
      category: 'Pasta',
      isVegetarian: true,
      ingredients: ['Fettuccine', 'Heavy Cream', 'Parmesan', 'Butter', 'Garlic'],
    },
    {
      name: 'Lasagna Bolognese',
      description: 'Layers of pasta, meat sauce, and cheese',
      imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800',
      price: 17.99,
      category: 'Pasta',
      isVegetarian: false,
      ingredients: ['Lasagna Sheets', 'Beef', 'Tomato Sauce', 'Ricotta', 'Mozzarella'],
    },
    {
      name: 'Penne Arrabbiata',
      description: 'Spicy tomato sauce with garlic and red peppers',
      imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800',
      price: 14.99,
      category: 'Pasta',
      isVegetarian: true,
      ingredients: ['Penne', 'Tomatoes', 'Garlic', 'Red Chili', 'Olive Oil'],
    },
    {
      name: 'Chicken Parmigiana',
      description: 'Breaded chicken with marinara and melted cheese',
      imageUrl: 'https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=800',
      price: 18.99,
      category: 'Main Course',
      isVegetarian: false,
      ingredients: ['Chicken Breast', 'Marinara', 'Mozzarella', 'Parmesan', 'Basil'],
    },
  ],
  chinese: [
    {
      name: 'Kung Pao Chicken',
      description: 'Spicy stir-fried chicken with peanuts and vegetables',
      imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800',
      price: 14.99,
      category: 'Main Course',
      isVegetarian: false,
      ingredients: ['Chicken', 'Peanuts', 'Chili Peppers', 'Szechuan Sauce'],
    },
    {
      name: 'Sweet and Sour Pork',
      description: 'Crispy pork with tangy sweet and sour sauce',
      imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800',
      price: 15.99,
      category: 'Main Course',
      isVegetarian: false,
      ingredients: ['Pork', 'Pineapple', 'Bell Peppers', 'Sweet & Sour Sauce'],
    },
    {
      name: 'Beef with Broccoli',
      description: 'Tender beef and broccoli in brown sauce',
      imageUrl: 'https://images.unsplash.com/photo-1603073052583-f05b60437e10?w=800',
      price: 16.99,
      category: 'Main Course',
      isVegetarian: false,
      ingredients: ['Beef', 'Broccoli', 'Oyster Sauce', 'Ginger', 'Garlic'],
    },
    {
      name: 'Vegetable Fried Rice',
      description: 'Wok-fried rice with mixed vegetables and egg',
      imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800',
      price: 11.99,
      category: 'Rice & Noodles',
      isVegetarian: true,
      ingredients: ['Rice', 'Mixed Vegetables', 'Egg', 'Soy Sauce', 'Green Onion'],
    },
    {
      name: 'General Tso\'s Chicken',
      description: 'Crispy chicken in sweet and spicy sauce',
      imageUrl: 'https://images.unsplash.com/photo-1596797882870-c6d6b888b4b2?w=800',
      price: 15.99,
      category: 'Main Course',
      isVegetarian: false,
      ingredients: ['Chicken', 'Soy Sauce', 'Ginger', 'Garlic', 'Dried Chilies'],
    },
  ],
  japanese: [
    {
      name: 'California Roll',
      description: 'Imitation crab, avocado, and cucumber',
      imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800',
      price: 12.99,
      category: 'Sushi',
      isVegetarian: false,
      ingredients: ['Sushi Rice', 'Nori', 'Imitation Crab', 'Avocado', 'Cucumber'],
    },
    {
      name: 'Spicy Tuna Roll',
      description: 'Fresh tuna with spicy mayo',
      imageUrl: 'https://images.unsplash.com/photo-1617196035796-f8ef6b7d01c6?w=800',
      price: 14.99,
      category: 'Sushi',
      isVegetarian: false,
      ingredients: ['Tuna', 'Spicy Mayo', 'Sushi Rice', 'Nori', 'Sesame Seeds'],
    },
    {
      name: 'Dragon Roll',
      description: 'Shrimp tempura with avocado and eel sauce',
      imageUrl: 'https://images.unsplash.com/photo-1563612116625-3012372fccce?w=800',
      price: 16.99,
      category: 'Sushi',
      isVegetarian: false,
      ingredients: ['Shrimp Tempura', 'Avocado', 'Eel Sauce', 'Sushi Rice', 'Tobiko'],
    },
    {
      name: 'Salmon Sashimi',
      description: 'Fresh sliced salmon (8 pieces)',
      imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800',
      price: 17.99,
      category: 'Sashimi',
      isVegetarian: false,
      ingredients: ['Fresh Salmon'],
    },
    {
      name: 'Vegetable Tempura',
      description: 'Lightly battered and fried vegetables',
      imageUrl: 'https://images.unsplash.com/photo-1541136455163-d6e2ea50c1e0?w=800',
      price: 10.99,
      category: 'Appetizers',
      isVegetarian: true,
      ingredients: ['Sweet Potato', 'Zucchini', 'Carrot', 'Tempura Batter'],
    },
  ],
  ramen: [
    {
      name: 'Tonkotsu Ramen',
      description: 'Rich pork bone broth with chashu pork',
      imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800',
      price: 14.99,
      category: 'Ramen',
      isVegetarian: false,
      ingredients: ['Pork Broth', 'Ramen Noodles', 'Chashu Pork', 'Soft Boiled Egg', 'Green Onion'],
    },
    {
      name: 'Spicy Miso Ramen',
      description: 'Miso broth with spicy paste and vegetables',
      imageUrl: 'https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=800',
      price: 13.99,
      category: 'Ramen',
      isVegetarian: false,
      ingredients: ['Miso Broth', 'Ramen Noodles', 'Spicy Paste', 'Corn', 'Bean Sprouts'],
    },
    {
      name: 'Shoyu Ramen',
      description: 'Soy sauce based broth with chicken',
      imageUrl: 'https://images.unsplash.com/photo-1623341214825-9f4f4156e58b?w=800',
      price: 13.99,
      category: 'Ramen',
      isVegetarian: false,
      ingredients: ['Soy Broth', 'Ramen Noodles', 'Chicken', 'Bamboo Shoots', 'Nori'],
    },
    {
      name: 'Vegetable Ramen',
      description: 'Light vegetable broth with seasonal vegetables',
      imageUrl: 'https://images.unsplash.com/photo-1591814468924-caf88d1232e1?w=800',
      price: 12.99,
      category: 'Ramen',
      isVegetarian: true,
      ingredients: ['Vegetable Broth', 'Ramen Noodles', 'Bok Choy', 'Mushrooms', 'Tofu'],
    },
    {
      name: 'Tsukemen',
      description: 'Dipping ramen with thick noodles',
      imageUrl: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=800',
      price: 15.99,
      category: 'Ramen',
      isVegetarian: false,
      ingredients: ['Thick Noodles', 'Dipping Sauce', 'Chashu', 'Egg', 'Menma'],
    },
  ],
  thai: [
    {
      name: 'Pad Thai',
      description: 'Stir-fried rice noodles with shrimp and peanuts',
      imageUrl: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800',
      price: 13.99,
      category: 'Noodles',
      isVegetarian: false,
      ingredients: ['Rice Noodles', 'Shrimp', 'Egg', 'Bean Sprouts', 'Peanuts', 'Tamarind'],
    },
    {
      name: 'Green Curry',
      description: 'Spicy green curry with chicken and coconut milk',
      imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800',
      price: 14.99,
      category: 'Curry',
      isVegetarian: false,
      ingredients: ['Green Curry Paste', 'Chicken', 'Coconut Milk', 'Basil', 'Bamboo'],
    },
    {
      name: 'Tom Yum Soup',
      description: 'Hot and sour soup with shrimp',
      imageUrl: 'https://images.unsplash.com/photo-1547928576-6a2f01c0da6d?w=800',
      price: 12.99,
      category: 'Soup',
      isVegetarian: false,
      ingredients: ['Shrimp', 'Lemongrass', 'Galangal', 'Kaffir Lime', 'Chili'],
    },
    {
      name: 'Mango Sticky Rice',
      description: 'Sweet sticky rice with fresh mango and coconut cream',
      imageUrl: 'https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=800',
      price: 8.99,
      category: 'Dessert',
      isVegetarian: true,
      ingredients: ['Sticky Rice', 'Fresh Mango', 'Coconut Cream', 'Sugar'],
    },
    {
      name: 'Pad See Ew',
      description: 'Wide rice noodles with Chinese broccoli and soy sauce',
      imageUrl: 'https://images.unsplash.com/photo-1569562211093-4ed0d0758f12?w=800',
      price: 13.99,
      category: 'Noodles',
      isVegetarian: false,
      ingredients: ['Wide Noodles', 'Chinese Broccoli', 'Beef', 'Soy Sauce', 'Garlic'],
    },
  ],
  korean: [
    {
      name: 'Bulgogi',
      description: 'Marinated beef with sweet soy sauce',
      imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800',
      price: 16.99,
      category: 'Main Course',
      isVegetarian: false,
      ingredients: ['Beef', 'Soy Sauce', 'Sesame Oil', 'Garlic', 'Pear'],
    },
    {
      name: 'Bibimbap',
      description: 'Mixed rice bowl with vegetables and fried egg',
      imageUrl: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=800',
      price: 14.99,
      category: 'Rice Bowls',
      isVegetarian: true,
      ingredients: ['Rice', 'Vegetables', 'Gochujang', 'Fried Egg', 'Sesame Oil'],
    },
    {
      name: 'Korean Fried Chicken',
      description: 'Crispy chicken with sweet and spicy glaze',
      imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=800',
      price: 15.99,
      category: 'Chicken',
      isVegetarian: false,
      ingredients: ['Chicken', 'Gochugaru', 'Honey', 'Soy Sauce', 'Garlic'],
    },
    {
      name: 'Kimchi Jjigae',
      description: 'Spicy kimchi stew with pork and tofu',
      imageUrl: 'https://images.unsplash.com/photo-1582525257861-bbb7ae6c5155?w=800',
      price: 13.99,
      category: 'Soup',
      isVegetarian: false,
      ingredients: ['Kimchi', 'Pork', 'Tofu', 'Gochugaru', 'Green Onion'],
    },
    {
      name: 'Japchae',
      description: 'Stir-fried glass noodles with vegetables',
      imageUrl: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800',
      price: 12.99,
      category: 'Noodles',
      isVegetarian: true,
      ingredients: ['Sweet Potato Noodles', 'Vegetables', 'Soy Sauce', 'Sesame Oil'],
    },
  ],
  vietnamese: [
    {
      name: 'Pho Bo',
      description: 'Traditional beef noodle soup with herbs',
      imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800',
      price: 13.99,
      category: 'Soup',
      isVegetarian: false,
      ingredients: ['Rice Noodles', 'Beef', 'Star Anise', 'Cilantro', 'Bean Sprouts'],
    },
    {
      name: 'Banh Mi',
      description: 'Vietnamese sandwich with pork and pickled vegetables',
      imageUrl: 'https://images.unsplash.com/photo-1598182198871-d3f4ab4fd181?w=800',
      price: 9.99,
      category: 'Sandwiches',
      isVegetarian: false,
      ingredients: ['Baguette', 'Pork', 'Pickled Carrots', 'Cucumber', 'Cilantro', 'Jalapeño'],
    },
    {
      name: 'Bun Cha',
      description: 'Grilled pork with vermicelli noodles',
      imageUrl: 'https://images.unsplash.com/photo-1569562211093-4ed0d0758f12?w=800',
      price: 14.99,
      category: 'Noodles',
      isVegetarian: false,
      ingredients: ['Vermicelli', 'Grilled Pork', 'Fish Sauce', 'Herbs', 'Pickles'],
    },
    {
      name: 'Spring Rolls',
      description: 'Fresh rice paper rolls with shrimp and vegetables',
      imageUrl: 'https://images.unsplash.com/photo-1569562211093-4ed0d0758f12?w=800',
      price: 8.99,
      category: 'Appetizers',
      isVegetarian: false,
      ingredients: ['Rice Paper', 'Shrimp', 'Lettuce', 'Mint', 'Vermicelli'],
    },
    {
      name: 'Com Tam',
      description: 'Broken rice with grilled pork chop',
      imageUrl: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?w=800',
      price: 12.99,
      category: 'Rice Bowls',
      isVegetarian: false,
      ingredients: ['Broken Rice', 'Pork Chop', 'Fried Egg', 'Pickled Vegetables'],
    },
  ],
  mexican: [
    {
      name: 'Chicken Tacos',
      description: 'Three soft tacos with grilled chicken and salsa',
      imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
      price: 11.99,
      category: 'Tacos',
      isVegetarian: false,
      ingredients: ['Tortillas', 'Chicken', 'Cilantro', 'Onion', 'Salsa Verde'],
    },
    {
      name: 'Beef Burrito',
      description: 'Large flour tortilla filled with beef, rice, and beans',
      imageUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800',
      price: 13.99,
      category: 'Burritos',
      isVegetarian: false,
      ingredients: ['Flour Tortilla', 'Beef', 'Rice', 'Black Beans', 'Cheese', 'Sour Cream'],
    },
    {
      name: 'Chicken Quesadilla',
      description: 'Grilled tortilla with chicken and melted cheese',
      imageUrl: 'https://images.unsplash.com/photo-1618040996337-56904b7850b9?w=800',
      price: 10.99,
      category: 'Quesadillas',
      isVegetarian: false,
      ingredients: ['Tortilla', 'Chicken', 'Cheese', 'Bell Peppers', 'Onions'],
    },
    {
      name: 'Carne Asada',
      description: 'Grilled marinated steak with rice and beans',
      imageUrl: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=800',
      price: 17.99,
      category: 'Main Course',
      isVegetarian: false,
      ingredients: ['Grilled Steak', 'Rice', 'Beans', 'Guacamole', 'Pico de Gallo'],
    },
    {
      name: 'Veggie Enchiladas',
      description: 'Corn tortillas filled with vegetables and cheese',
      imageUrl: 'https://images.unsplash.com/photo-1617343267882-fa5816fe6951?w=800',
      price: 12.99,
      category: 'Enchiladas',
      isVegetarian: true,
      ingredients: ['Corn Tortillas', 'Mixed Vegetables', 'Cheese', 'Enchilada Sauce'],
    },
  ],
  indian: [
    {
      name: 'Butter Chicken',
      description: 'Tender chicken in creamy tomato sauce',
      imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800',
      price: 15.99,
      category: 'Curry',
      isVegetarian: false,
      ingredients: ['Chicken', 'Tomato', 'Cream', 'Butter', 'Garam Masala'],
    },
    {
      name: 'Chicken Tikka Masala',
      description: 'Marinated chicken in spiced curry sauce',
      imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800',
      price: 16.99,
      category: 'Curry',
      isVegetarian: false,
      ingredients: ['Chicken', 'Yogurt', 'Tomato Sauce', 'Spices', 'Cream'],
    },
    {
      name: 'Palak Paneer',
      description: 'Spinach curry with Indian cottage cheese',
      imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800',
      price: 13.99,
      category: 'Curry',
      isVegetarian: true,
      ingredients: ['Spinach', 'Paneer', 'Cream', 'Garlic', 'Ginger'],
    },
    {
      name: 'Lamb Biryani',
      description: 'Fragrant basmati rice with spiced lamb',
      imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800',
      price: 18.99,
      category: 'Rice',
      isVegetarian: false,
      ingredients: ['Basmati Rice', 'Lamb', 'Saffron', 'Yogurt', 'Spices'],
    },
    {
      name: 'Garlic Naan',
      description: 'Fresh tandoor-baked bread with garlic',
      imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800',
      price: 4.99,
      category: 'Bread',
      isVegetarian: true,
      ingredients: ['Flour', 'Garlic', 'Butter', 'Yogurt'],
    },
  ],
  mediterranean: [
    {
      name: 'Chicken Gyro',
      description: 'Grilled chicken in pita with tzatziki sauce',
      imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
      price: 12.99,
      category: 'Wraps',
      isVegetarian: false,
      ingredients: ['Pita Bread', 'Chicken', 'Tzatziki', 'Lettuce', 'Tomato', 'Onion'],
    },
    {
      name: 'Falafel Plate',
      description: 'Crispy chickpea fritters with hummus and tahini',
      imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
      price: 11.99,
      category: 'Main Course',
      isVegetarian: true,
      ingredients: ['Falafel', 'Hummus', 'Tahini', 'Pita', 'Salad'],
    },
    {
      name: 'Greek Salad',
      description: 'Fresh vegetables with feta cheese and olives',
      imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
      price: 9.99,
      category: 'Salads',
      isVegetarian: true,
      ingredients: ['Lettuce', 'Tomato', 'Cucumber', 'Feta', 'Olives', 'Olive Oil'],
    },
    {
      name: 'Lamb Kebab',
      description: 'Grilled lamb skewers with rice pilaf',
      imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
      price: 17.99,
      category: 'Main Course',
      isVegetarian: false,
      ingredients: ['Lamb', 'Rice', 'Grilled Vegetables', 'Mint Sauce'],
    },
    {
      name: 'Spanakopita',
      description: 'Flaky pastry filled with spinach and feta',
      imageUrl: 'https://images.unsplash.com/photo-1628863353691-0071c8c1874c?w=800',
      price: 10.99,
      category: 'Appetizers',
      isVegetarian: true,
      ingredients: ['Phyllo Dough', 'Spinach', 'Feta', 'Onion', 'Dill'],
    },
  ],
  bbq: [
    {
      name: 'BBQ Pulled Pork',
      description: 'Slow-smoked pulled pork with coleslaw',
      imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
      price: 16.99,
      category: 'BBQ',
      isVegetarian: false,
      ingredients: ['Pulled Pork', 'BBQ Sauce', 'Coleslaw', 'Brioche Bun'],
    },
    {
      name: 'Beef Brisket',
      description: 'Texas-style smoked brisket',
      imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
      price: 19.99,
      category: 'BBQ',
      isVegetarian: false,
      ingredients: ['Beef Brisket', 'Dry Rub', 'Pickles', 'Onions'],
    },
    {
      name: 'BBQ Ribs',
      description: 'Fall-off-the-bone baby back ribs',
      imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
      price: 22.99,
      category: 'BBQ',
      isVegetarian: false,
      ingredients: ['Baby Back Ribs', 'BBQ Sauce', 'Spice Rub'],
    },
    {
      name: 'Smoked Chicken',
      description: 'Half chicken smoked to perfection',
      imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800',
      price: 14.99,
      category: 'BBQ',
      isVegetarian: false,
      ingredients: ['Chicken', 'BBQ Rub', 'BBQ Sauce'],
    },
    {
      name: 'Mac and Cheese',
      description: 'Creamy macaroni with smoked cheddar',
      imageUrl: 'https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?w=800',
      price: 7.99,
      category: 'Sides',
      isVegetarian: true,
      ingredients: ['Macaroni', 'Smoked Cheddar', 'Cream', 'Breadcrumbs'],
    },
  ],
  steak: [
    {
      name: 'Ribeye Steak',
      description: '12oz aged ribeye cooked to your preference',
      imageUrl: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800',
      price: 32.99,
      category: 'Steaks',
      isVegetarian: false,
      ingredients: ['Ribeye', 'Sea Salt', 'Black Pepper', 'Garlic Butter'],
    },
    {
      name: 'Filet Mignon',
      description: '8oz tender beef filet with demi-glace',
      imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800',
      price: 34.99,
      category: 'Steaks',
      isVegetarian: false,
      ingredients: ['Filet Mignon', 'Demi-Glace', 'Herb Butter'],
    },
    {
      name: 'New York Strip',
      description: '14oz classic strip steak',
      imageUrl: 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=800',
      price: 29.99,
      category: 'Steaks',
      isVegetarian: false,
      ingredients: ['NY Strip', 'Garlic', 'Rosemary', 'Thyme'],
    },
    {
      name: 'Surf and Turf',
      description: 'Filet mignon with grilled lobster tail',
      imageUrl: 'https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?w=800',
      price: 42.99,
      category: 'Steaks',
      isVegetarian: false,
      ingredients: ['Filet Mignon', 'Lobster Tail', 'Lemon Butter'],
    },
    {
      name: 'Loaded Baked Potato',
      description: 'Baked potato with bacon, cheese, and sour cream',
      imageUrl: 'https://images.unsplash.com/photo-1518013431117-eb1465fa5752?w=800',
      price: 6.99,
      category: 'Sides',
      isVegetarian: false,
      ingredients: ['Potato', 'Bacon', 'Cheddar', 'Sour Cream', 'Chives'],
    },
  ],
  seafood: [
    {
      name: 'Fish and Chips',
      description: 'Beer-battered cod with crispy fries',
      imageUrl: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=800',
      price: 15.99,
      category: 'Main Course',
      isVegetarian: false,
      ingredients: ['Cod', 'Beer Batter', 'Fries', 'Tartar Sauce', 'Lemon'],
    },
    {
      name: 'Grilled Salmon',
      description: 'Atlantic salmon with lemon herb butter',
      imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
      price: 19.99,
      category: 'Main Course',
      isVegetarian: false,
      ingredients: ['Salmon', 'Lemon', 'Herbs', 'Butter', 'Asparagus'],
    },
    {
      name: 'Shrimp Scampi',
      description: 'Garlic butter shrimp over pasta',
      imageUrl: 'https://images.unsplash.com/photo-1633504581786-316c8b5ee095?w=800',
      price: 17.99,
      category: 'Main Course',
      isVegetarian: false,
      ingredients: ['Shrimp', 'Garlic', 'Butter', 'White Wine', 'Linguine'],
    },
    {
      name: 'Lobster Roll',
      description: 'Fresh lobster salad in a toasted bun',
      imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
      price: 24.99,
      category: 'Sandwiches',
      isVegetarian: false,
      ingredients: ['Lobster', 'Mayo', 'Celery', 'Lemon', 'Butter Roll'],
    },
    {
      name: 'Clam Chowder',
      description: 'Creamy New England style chowder',
      imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
      price: 8.99,
      category: 'Soup',
      isVegetarian: false,
      ingredients: ['Clams', 'Potatoes', 'Cream', 'Bacon', 'Celery'],
    },
  ],
  healthy: [
    {
      name: 'Buddha Bowl',
      description: 'Quinoa bowl with roasted vegetables and tahini',
      imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
      price: 13.99,
      category: 'Bowls',
      isVegetarian: true,
      ingredients: ['Quinoa', 'Sweet Potato', 'Chickpeas', 'Kale', 'Tahini'],
    },
    {
      name: 'Açai Bowl',
      description: 'Açai smoothie bowl with fresh fruits and granola',
      imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800',
      price: 11.99,
      category: 'Bowls',
      isVegetarian: true,
      ingredients: ['Açai', 'Banana', 'Berries', 'Granola', 'Honey'],
    },
    {
      name: 'Grilled Chicken Salad',
      description: 'Mixed greens with grilled chicken and balsamic',
      imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
      price: 12.99,
      category: 'Salads',
      isVegetarian: false,
      ingredients: ['Chicken', 'Mixed Greens', 'Cherry Tomatoes', 'Balsamic', 'Avocado'],
    },
    {
      name: 'Green Smoothie',
      description: 'Spinach, mango, banana, and chia seeds',
      imageUrl: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=800',
      price: 7.99,
      category: 'Drinks',
      isVegetarian: true,
      ingredients: ['Spinach', 'Mango', 'Banana', 'Chia Seeds', 'Almond Milk'],
    },
    {
      name: 'Protein Power Bowl',
      description: 'Grilled chicken, brown rice, and vegetables',
      imageUrl: 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=800',
      price: 14.99,
      category: 'Bowls',
      isVegetarian: false,
      ingredients: ['Grilled Chicken', 'Brown Rice', 'Broccoli', 'Quinoa', 'Avocado'],
    },
  ],
  breakfast: [
    {
      name: 'Classic Pancakes',
      description: 'Fluffy pancakes with maple syrup and butter',
      imageUrl: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=800',
      price: 9.99,
      category: 'Breakfast',
      isVegetarian: true,
      ingredients: ['Pancakes', 'Maple Syrup', 'Butter', 'Berries'],
    },
    {
      name: 'Eggs Benedict',
      description: 'Poached eggs on English muffin with hollandaise',
      imageUrl: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=800',
      price: 13.99,
      category: 'Breakfast',
      isVegetarian: false,
      ingredients: ['Poached Eggs', 'English Muffin', 'Ham', 'Hollandaise'],
    },
    {
      name: 'Avocado Toast',
      description: 'Smashed avocado on sourdough with poached egg',
      imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800',
      price: 11.99,
      category: 'Breakfast',
      isVegetarian: true,
      ingredients: ['Sourdough', 'Avocado', 'Poached Egg', 'Cherry Tomatoes'],
    },
    {
      name: 'French Toast',
      description: 'Thick brioche French toast with berries',
      imageUrl: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800',
      price: 10.99,
      category: 'Breakfast',
      isVegetarian: true,
      ingredients: ['Brioche', 'Eggs', 'Cinnamon', 'Berries', 'Powdered Sugar'],
    },
    {
      name: 'Breakfast Burrito',
      description: 'Scrambled eggs, bacon, cheese, and salsa',
      imageUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800',
      price: 12.99,
      category: 'Breakfast',
      isVegetarian: false,
      ingredients: ['Tortilla', 'Eggs', 'Bacon', 'Cheese', 'Salsa', 'Hash Browns'],
    },
  ],
  sandwich: [
    {
      name: 'Club Sandwich',
      description: 'Triple-decker with turkey, bacon, and avocado',
      imageUrl: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=800',
      price: 11.99,
      category: 'Sandwiches',
      isVegetarian: false,
      ingredients: ['Turkey', 'Bacon', 'Avocado', 'Lettuce', 'Tomato', 'Mayo'],
    },
    {
      name: 'Philly Cheesesteak',
      description: 'Thinly sliced steak with melted cheese',
      imageUrl: 'https://images.unsplash.com/photo-1568357399606-99330d4e8084?w=800',
      price: 13.99,
      category: 'Sandwiches',
      isVegetarian: false,
      ingredients: ['Steak', 'Provolone', 'Onions', 'Peppers', 'Hoagie Roll'],
    },
    {
      name: 'Caprese Panini',
      description: 'Fresh mozzarella, tomato, and basil pressed',
      imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800',
      price: 10.99,
      category: 'Sandwiches',
      isVegetarian: true,
      ingredients: ['Mozzarella', 'Tomato', 'Basil', 'Balsamic', 'Ciabatta'],
    },
    {
      name: 'Reuben Sandwich',
      description: 'Corned beef, sauerkraut, Swiss, and Russian dressing',
      imageUrl: 'https://images.unsplash.com/photo-1619365734072-04bda7e31f5a?w=800',
      price: 12.99,
      category: 'Sandwiches',
      isVegetarian: false,
      ingredients: ['Corned Beef', 'Sauerkraut', 'Swiss Cheese', 'Russian Dressing', 'Rye'],
    },
    {
      name: 'BLT',
      description: 'Crispy bacon, lettuce, and tomato on toasted bread',
      imageUrl: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?w=800',
      price: 9.99,
      category: 'Sandwiches',
      isVegetarian: false,
      ingredients: ['Bacon', 'Lettuce', 'Tomato', 'Mayo', 'Toasted Bread'],
    },
  ],
  dessert: [
    {
      name: 'Chocolate Lava Cake',
      description: 'Warm chocolate cake with molten center',
      imageUrl: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800',
      price: 8.99,
      category: 'Desserts',
      isVegetarian: true,
      ingredients: ['Chocolate', 'Eggs', 'Butter', 'Sugar', 'Vanilla Ice Cream'],
    },
    {
      name: 'New York Cheesecake',
      description: 'Classic creamy cheesecake with berry compote',
      imageUrl: 'https://images.unsplash.com/photo-1567327326340-83eb79de0ca4?w=800',
      price: 7.99,
      category: 'Desserts',
      isVegetarian: true,
      ingredients: ['Cream Cheese', 'Graham Cracker', 'Sour Cream', 'Berries'],
    },
    {
      name: 'Tiramisu',
      description: 'Italian coffee-flavored layered dessert',
      imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800',
      price: 8.99,
      category: 'Desserts',
      isVegetarian: true,
      ingredients: ['Ladyfingers', 'Espresso', 'Mascarpone', 'Cocoa Powder'],
    },
    {
      name: 'Crème Brûlée',
      description: 'Vanilla custard with caramelized sugar top',
      imageUrl: 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=800',
      price: 9.99,
      category: 'Desserts',
      isVegetarian: true,
      ingredients: ['Cream', 'Egg Yolks', 'Vanilla', 'Sugar'],
    },
    {
      name: 'Apple Pie',
      description: 'Classic apple pie with vanilla ice cream',
      imageUrl: 'https://images.unsplash.com/photo-1535920527002-b35e96722eb9?w=800',
      price: 6.99,
      category: 'Desserts',
      isVegetarian: true,
      ingredients: ['Apples', 'Cinnamon', 'Pie Crust', 'Vanilla Ice Cream'],
    },
  ],
  wings: [
    {
      name: 'Buffalo Wings',
      description: 'Classic buffalo wings with blue cheese',
      imageUrl: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=800',
      price: 12.99,
      category: 'Wings',
      isVegetarian: false,
      ingredients: ['Chicken Wings', 'Buffalo Sauce', 'Blue Cheese', 'Celery'],
    },
    {
      name: 'BBQ Wings',
      description: 'Smoky BBQ glazed wings',
      imageUrl: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=800',
      price: 12.99,
      category: 'Wings',
      isVegetarian: false,
      ingredients: ['Chicken Wings', 'BBQ Sauce', 'Ranch'],
    },
    {
      name: 'Honey Garlic Wings',
      description: 'Sweet and savory honey garlic wings',
      imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=800',
      price: 12.99,
      category: 'Wings',
      isVegetarian: false,
      ingredients: ['Chicken Wings', 'Honey', 'Garlic', 'Soy Sauce'],
    },
    {
      name: 'Spicy Korean Wings',
      description: 'Gochujang glazed wings with sesame',
      imageUrl: 'https://images.unsplash.com/photo-1626082924459-76fa1d4ca2d4?w=800',
      price: 13.99,
      category: 'Wings',
      isVegetarian: false,
      ingredients: ['Chicken Wings', 'Gochujang', 'Honey', 'Sesame Seeds'],
    },
    {
      name: 'Lemon Pepper Wings',
      description: 'Crispy wings with lemon pepper seasoning',
      imageUrl: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800',
      price: 12.99,
      category: 'Wings',
      isVegetarian: false,
      ingredients: ['Chicken Wings', 'Lemon', 'Black Pepper', 'Butter'],
    },
  ],
  fusion: [
    {
      name: 'Korean BBQ Tacos',
      description: 'Bulgogi beef in soft tacos with kimchi',
      imageUrl: 'https://images.unsplash.com/photo-1564767655658-4e6b365884ff?w=800',
      price: 14.99,
      category: 'Fusion',
      isVegetarian: false,
      ingredients: ['Bulgogi Beef', 'Tortillas', 'Kimchi', 'Cilantro', 'Gochujang Mayo'],
    },
    {
      name: 'Sushi Burrito',
      description: 'Giant sushi roll wrapped like a burrito',
      imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800',
      price: 13.99,
      category: 'Fusion',
      isVegetarian: false,
      ingredients: ['Sushi Rice', 'Nori', 'Salmon', 'Avocado', 'Spicy Mayo'],
    },
    {
      name: 'Thai Basil Pizza',
      description: 'Pizza with Thai curry sauce and basil',
      imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
      price: 16.99,
      category: 'Fusion',
      isVegetarian: false,
      ingredients: ['Pizza Dough', 'Thai Curry', 'Chicken', 'Thai Basil', 'Mozzarella'],
    },
    {
      name: 'Ramen Burger',
      description: 'Burger with ramen noodle buns',
      imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800',
      price: 15.99,
      category: 'Fusion',
      isVegetarian: false,
      ingredients: ['Beef Patty', 'Ramen Noodle Buns', 'Lettuce', 'Teriyaki Sauce'],
    },
    {
      name: 'Pho French Dip',
      description: 'French dip sandwich with pho broth',
      imageUrl: 'https://images.unsplash.com/photo-1567327334500-3458b15b369a?w=800',
      price: 14.99,
      category: 'Fusion',
      isVegetarian: false,
      ingredients: ['Beef', 'Baguette', 'Pho Broth', 'Onions', 'Hoisin'],
    },
  ],
  caribbean: [
    {
      name: 'Jerk Chicken',
      description: 'Spicy Jamaican jerk chicken with rice and beans',
      imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800',
      price: 15.99,
      category: 'Main Course',
      isVegetarian: false,
      ingredients: ['Chicken', 'Jerk Spice', 'Rice', 'Beans', 'Plantains'],
    },
    {
      name: 'Curry Goat',
      description: 'Tender goat meat in aromatic curry',
      imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800',
      price: 17.99,
      category: 'Main Course',
      isVegetarian: false,
      ingredients: ['Goat', 'Curry Powder', 'Potatoes', 'Scotch Bonnet', 'Rice'],
    },
    {
      name: 'Fried Plantains',
      description: 'Sweet fried plantains',
      imageUrl: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800',
      price: 6.99,
      category: 'Sides',
      isVegetarian: true,
      ingredients: ['Plantains', 'Oil', 'Cinnamon Sugar'],
    },
    {
      name: 'Oxtail Stew',
      description: 'Slow-cooked oxtail in rich gravy',
      imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
      price: 18.99,
      category: 'Main Course',
      isVegetarian: false,
      ingredients: ['Oxtail', 'Butter Beans', 'Carrots', 'Thyme', 'Rice'],
    },
    {
      name: 'Conch Fritters',
      description: 'Crispy fried conch balls',
      imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800',
      price: 11.99,
      category: 'Appetizers',
      isVegetarian: false,
      ingredients: ['Conch', 'Bell Peppers', 'Onion', 'Scotch Bonnet', 'Aioli'],
    },
  ],
  comfort: [
    {
      name: 'Chicken Pot Pie',
      description: 'Creamy chicken and vegetables in flaky crust',
      imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
      price: 14.99,
      category: 'Main Course',
      isVegetarian: false,
      ingredients: ['Chicken', 'Vegetables', 'Cream Sauce', 'Pie Crust'],
    },
    {
      name: 'Meatloaf',
      description: 'Classic meatloaf with mashed potatoes',
      imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
      price: 13.99,
      category: 'Main Course',
      isVegetarian: false,
      ingredients: ['Ground Beef', 'Breadcrumbs', 'Ketchup', 'Mashed Potatoes'],
    },
    {
      name: 'Mac & Cheese',
      description: 'Creamy baked macaroni and cheese',
      imageUrl: 'https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?w=800',
      price: 10.99,
      category: 'Main Course',
      isVegetarian: true,
      ingredients: ['Macaroni', 'Cheddar', 'Cream', 'Breadcrumbs'],
    },
    {
      name: 'Fried Chicken',
      description: 'Buttermilk fried chicken with biscuits',
      imageUrl: 'https://images.unsplash.com/photo-1626082924459-76fa1d4ca2d4?w=800',
      price: 15.99,
      category: 'Main Course',
      isVegetarian: false,
      ingredients: ['Chicken', 'Buttermilk', 'Flour', 'Spices', 'Biscuits'],
    },
    {
      name: 'Shepherd\'s Pie',
      description: 'Ground beef with vegetables and mashed potato topping',
      imageUrl: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800',
      price: 14.99,
      category: 'Main Course',
      isVegetarian: false,
      ingredients: ['Ground Beef', 'Peas', 'Carrots', 'Gravy', 'Mashed Potatoes'],
    },
  ],
};

// Map restaurant categories to menu types
const categoryToMenuType: Record<string, string> = {
  'Burger': 'burger',
  'Pizza': 'pizza',
  'Italian': 'italian',
  'Pasta': 'italian',
  'Chinese': 'chinese',
  'Dim Sum': 'chinese',
  'Japanese': 'japanese',
  'Sushi': 'japanese',
  'Ramen': 'ramen',
  'Thai': 'thai',
  'Korean': 'korean',
  'Vietnamese': 'vietnamese',
  'Mexican': 'mexican',
  'Indian': 'indian',
  'Mediterranean': 'mediterranean',
  'Greek': 'mediterranean',
  'Middle Eastern': 'mediterranean',
  'BBQ': 'bbq',
  'Steakhouse': 'steak',
  'Seafood': 'seafood',
  'Vegan': 'healthy',
  'Healthy': 'healthy',
  'Breakfast': 'breakfast',
  'Brunch': 'breakfast',
  'Sandwiches': 'sandwich',
  'Deli': 'sandwich',
  'Dessert': 'dessert',
  'Bakery': 'dessert',
  'Chicken': 'wings',
  'Fast Food': 'wings',
  'Comfort Food': 'comfort',
  'Fusion': 'fusion',
  'Caribbean': 'caribbean',
};

const seedDatabase = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect(config.database.uri);
    logger.info('Connected to MongoDB');

    // Clear existing data
    await Restaurant.deleteMany({});
    await MenuItem.deleteMany({});
    logger.info('Cleared existing data');

    // Insert restaurants
    const createdRestaurants = await Restaurant.insertMany(restaurants);
    logger.info(`✅ Created ${createdRestaurants.length} restaurants`);

    // Create menu items for each restaurant
    let totalMenuItems = 0;
    for (const restaurant of createdRestaurants) {
      // Determine menu type based on categories
      const primaryCategory = restaurant.categories[0];
      const menuType = categoryToMenuType[primaryCategory] || 'comfort';
      const menuItems = menuItemsByType[menuType] || menuItemsByType.comfort;

      // Add random ratings and popularity
      const menuItemsWithData = menuItems.map((item) => ({
        ...item,
        restaurantId: (restaurant._id as any).toString(),
        rating: +(4.0 + Math.random() * 1).toFixed(1), // 4.0 - 5.0
        reviewCount: Math.floor(Math.random() * 200) + 50, // 50-250
        isPopular: Math.random() > 0.6, // 40% popular
      }));

      await MenuItem.insertMany(menuItemsWithData);
      totalMenuItems += menuItemsWithData.length;
      
      // Update restaurant with hasVegetarianOptions based on menu items
      const hasVegetarianOptions = menuItemsWithData.some((item) => item.isVegetarian);
      await Restaurant.findByIdAndUpdate(restaurant._id, { hasVegetarianOptions });
      
      logger.info(`  ✓ Created ${menuItemsWithData.length} menu items for ${restaurant.name}${hasVegetarianOptions ? ' (has vegetarian options)' : ''}`);
    }

    logger.info('');
    logger.info('🎉 Database seeded successfully!');
    logger.info(`📊 Summary:`);
    logger.info(`   - ${createdRestaurants.length} restaurants`);
    logger.info(`   - ${totalMenuItems} menu items`);
    logger.info(`   - Average ${(totalMenuItems / createdRestaurants.length).toFixed(1)} items per restaurant`);
    
    process.exit(0);
  } catch (error) {
    logger.error('❌ Error seeding database', { error });
    process.exit(1);
  }
};

// Run seed script
seedDatabase();
